hazelcast/hazelcast-kubernetes

README.adoc, src/main/java/com/noctarius/hazelcast/kubernetes/DnsEndpointResolver.java, src/main/java/com/noctarius/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategy.java, src/main/java/com/noctarius/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategyFactory.java, src/main/java/com/noctarius/hazelcast/kubernetes/KubernetesProperties.java, src/main/java/com/noctarius/hazelcast/kubernetes/ServiceEndpointResolver.java
- Update REST service discovery to query by labe & value or only by namespace
- use default Hazelcast port in DNS discovery when query returns 0
=> Update REST service discovery & Hazelcast port fallback in DNS discovery

src/main/java/com/noctarius/hazelcast/kubernetes/DnsEndpointResolver.java
In my case (GCE Kubernetes 1.3.5), lookup returns several records. To make things even worst, order of the records is not guaranteed. This lead to situation when all Hazecast nodes were separated in several not intersecting buckets. In edge case, node could discover only itself.
=> Traversing through complete set of returned DNS records

src/main/java/com/noctarius/hazelcast/kubernetes/DnsEndpointResolver.java
dnsjava uses a global DNS lookup cache. If the service DNS returns failures temporarily, these failure responses will be cached with an indefinite TTL by default, effectively disabling the Kubernetes service DNS lookup until the node is restarted.
This fix turns off the cache to get a fresh, current DNS response for each request.
=> Avoid caching temporary DNS lookup failures

pom.xml, src/main/java/com/noctarius/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategy.java, src/main/java/com/noctarius/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategyFactory.java, src/main/java/com/noctarius/hazelcast/kubernetes/KubernetesProperties.java, src/main/java/com/noctarius/hazelcast/kubernetes/ServiceEndpointResolver.java
Using the ServiceEndpointResolver it is convenient to have an option to configure the api-token directly via config. This pull requests covers this aspect. In the case of REST API Request the following configuration can be added to the <properties> section to specify the api-token to use:
<property name="api-token">isve1234LxyA2LALALAW256789P47H</property>
In case of missing property the currently existing implementation is used.
=> Extraction of api-token per param

README.adoc, src/main/java/com/noctarius/hazelcast/kubernetes/DnsEndpointResolver.java, src/main/java/com/noctarius/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategy.java, src/main/java/com/noctarius/hazelcast/kubernetes/KubernetesProperties.java
Adds a configuration property to set the DNS timeout. By default, dnsjava uses a globally shared default resolver, which in turn defaults to 5s. This PR makes this value configurable and avoids using the globally shared dnsjava resolver, which might be a good thing by itself to avoid interference with other code using dnsjava and changing global defaults. Together with the caching PR #22, this should make the plugin more resilient against stray DNS issues or slow responses.
=> Configurable DNS timeout

checkstyle/checkstyle.xml, src/main/java/com/hazelcast/kubernetes/ServiceEndpointResolver.java
Hi there,
I recently noticed a glitch in com.hazelcast.kubernetes.ServiceEndpointResolver.buildKubernetesClient(String, String): If the provided apiToken is empty, the code does load the token from file correctly but logs the "old" apiToken, which results in a misleading log entry.
=> OAuth Token Does Not Get Logged

README.adoc
The use of the KUBERNETES_NAMESPACE and OPENSHIFT_BUILD_NAMESPACE
environment variable have not been documented before. One had to look
into the implementation to find out they are supported.
=> Document environment variable usage in README.adoc

pom.xml, src/test/java/com/hazelcast/kubernetes/DnsEndpointResolverTest.java, src/test/java/com/hazelcast/kubernetes/ServiceEndpointResolverTest.java
Although the 1.x client works well, it should be beneficial to upgrade to the newest version.
I've run a smoke test successfully on GKE.
=> Upgrade kubernetes-client to version 3.x

src/main/java/com/hazelcast/kubernetes/DnsEndpointResolver.java, src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategy.java, src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategyFactory.java, src/main/java/com/hazelcast/kubernetes/KubernetesProperties.java, src/main/java/com/hazelcast/kubernetes/ServiceEndpointResolver.java, src/test/java/com/hazelcast/kubernetes/DnsEndpointResolverTest.java, src/test/java/com/hazelcast/kubernetes/KubernetesDiscoveryStrategyFactoryTest.java, src/test/java/com/hazelcast/kubernetes/ServiceEndpointResolverTest.java
Adding new plugin property "service-port". This is solution for issue #40 allowing to override the default port. The property is used in both DNS and REST resolver.
=> Adding service port configuration support

README.adoc
Fix the document about dns lookup which requires headless service name.
=> fix document issue #70, dns lookup requires headless

pom.xml
Hazelcast Version updated to 3.9.3, kubernetes client to 3.1.10, dnsjava to 2.1.8 and powermock to 1.7.3
=> Hazelcast Version updated to 3.9.3 and other version updates

src/main/java/com/hazelcast/kubernetes/DefaultKubernetesClient.java, src/main/java/com/hazelcast/kubernetes/KubernetesClient.java, src/main/java/com/hazelcast/kubernetes/RetryKubernetesClient.java, src/main/java/com/hazelcast/kubernetes/RetryUtils.java, src/main/java/com/hazelcast/kubernetes/ServiceEndpointResolver.java, src/test/java/com/hazelcast/kubernetes/DefaultKubernetesClientTest.java, src/test/java/com/hazelcast/kubernetes/DnsEndpointResolverTest.java, src/test/java/com/hazelcast/kubernetes/KubernetesDiscoveryStrategyFactoryTest.java, src/test/java/com/hazelcast/kubernetes/RetryKubernetesClientTest.java, src/test/java/com/hazelcast/kubernetes/RetryUtilsTest.java, src/test/java/com/hazelcast/kubernetes/ServiceEndpointResolverTest.java
Make each call to Kubernetes API retried in case of failures. It prevents issues when the Kubernetes Master is overloaded.
fix #78
fix #28
Changes:
- Extract interface `KubernetesClient`, so that there'd be `DefaultKubernetesClient` which implements `KubernetesClient`
- Create `RetryKubernetesClient` which uses Decorator Patter to "decorate" `KubernetesClient` with retries
Notes to reviewers:
- It may seem like a lot of code changes, but actually there is no code change in `KubernetesClient` and `DefaultKubernetesClient`, it's just renaming plus splitting into two classes; the only added code is actually `RetryUtils` and `RetryKubernetesClient`
- `RetryUtils` is almost identically copied from `hazelcast-aws` [1]; It seems like a bad sign and breaking SRP, but IMO this one class is not …
=> Add retries to REST calls to Kubernetes API

README.adoc
=> Update README to remove misleading "prior Hazelcast 3.8" information

pom.xml, src/main/java/com/hazelcast/kubernetes/DnsEndpointResolver.java, src/test/java/com/hazelcast/kubernetes/DnsEndpointResolverTest.java
fix #97 
The implementation is based on: https://nitschinger.at/Bootstrapping-from-DNS-SRV-records-in-Java/
Tested on PKS and GKE.
=> Remove 'dnsjava' dependency

src/test/java/com/hazelcast/kubernetes/DefaultKubernetesClientTest.java
The issue was that WireMock used a static port. This PR changes it to use dynamic port.
=> Fix Flaky Tests

README.md, src/main/java/com/hazelcast/kubernetes/DefaultKubernetesClient.java
fix https://github.com/hazelcast/hazelcast/issues/13760
The issue is that certain JRE implementations don't use TLSv1.2 by default, but uses TLSv1.0 by default. An example of that is IBM Java. By being specific, all JRE which supports TLS 1.2 should work fine.
Tested on: OpenJDK, Oracle, IBM.
After merging this PR, we'll need to do 2 releases:
- patch release from master (1.3.1)
- similar PR to the branch "maintenance-1.2.x" and patch release (1.2.1)
=> Use specific "TLSv1.2" instead of "TLS"

pom.xml
hazelcast-kubernetes was depending on hazelcast, since hazelcast-jet also depends on hazelcast there might be some clashes on the classpath when hazelcast-jet and hazelcast-kubernetes used together.
=> Changed hazelcast dependency scope to provided

pom.xml, src/main/java/com/hazelcast/kubernetes/DefaultKubernetesClient.java, src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategy.java, src/main/java/com/hazelcast/kubernetes/KubernetesApiEndpointResolver.java, src/main/java/com/hazelcast/kubernetes/KubernetesClient.java, src/main/java/com/hazelcast/kubernetes/RetryKubernetesClient.java, src/main/java/com/hazelcast/kubernetes/RetryUtils.java, src/test/java/com/hazelcast/kubernetes/DefaultKubernetesClientTest.java, src/test/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategyFactoryTest.java, src/test/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategyTest.java, src/test/java/com/hazelcast/kubernetes/KubernetesApiEndpointResolverTest.java, src/test/java/com/hazelcast/kubernetes/KubernetesDiscoveryStrategyTest.java, src/test/java/com/hazelcast/kubernetes/RetryKubernetesClientTest.java, src/test/java/com/hazelcast/kubernetes/RetryUtilsTest.java
Changes:
- Add retrieving zone name from Kubernetes API
- Refactor `HazelcastKubernetesDiscoveryStrategy` to include `namespace` and `KubernetesClient`
- Add non-retryable keywords to `RetryUtils` (prevents retrying exceptions caused by "reason:Forbidden")
=> Add ZONE_AWARE

src/main/java/com/hazelcast/kubernetes/DefaultKubernetesClient.java, src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategy.java, src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategyFactory.java, src/main/java/com/hazelcast/kubernetes/KubernetesProperties.java, src/test/java/com/hazelcast/kubernetes/DefaultKubernetesClientTest.java, src/test/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategyFactoryTest.java
This is the missing part of the external authentication to Kubernetes API (Kubernetes Master). Now you can use Kubernetes API from outside the cluster by defining the following properties:
- `kubernetes-master` - address of Kubernetes Master
- `api-token` - API Access Token to Kubernetes Master
- `ca-certificate` - CA Certificate to Kubernetes Master
The implementation allows you to specify the certificate by pasting the string directly into your `hazelcast.xml`, which looks quite ugly, like:
```
<ca-certificate>
-----BEGIN CERTIFICATE-----
MIIDDDCCAfSgAwIBAgIRAOlepQ2R2h/eyHYayR0AfLIwDQYJKoZIhvcNAQELBQAw
LzEtMCsGA1UEAxMkMzEyMDU1ZmYtZDhmZi00OGJiLTlhYmItMmZiZDFkZjlmY2Iz
MB4XDTE5MDEwODE0NDIxMVoXDTI0MDEwNzE1NDIxMVowLzEtMCsGA1UEAxMkMzEy …
```
=> Add "ca-certificate" property to define the custom Kubernetes Master CA

src/main/java/com/hazelcast/kubernetes/RetryUtils.java
The current message is misleading, because it mentioned Kubernetes master, which is not always the issue for retrying.
Related to #132
=> Change Retry error log message

README.md, src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategy.java, src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategyFactory.java, src/main/java/com/hazelcast/kubernetes/KubernetesClient.java, src/main/java/com/hazelcast/kubernetes/KubernetesProperties.java, src/test/java/com/hazelcast/kubernetes/KubernetesClientTest.java
Make the number of retries configurable and change the default value to 3.
Before, the number of retires was hardcoded to 10, which is high and if there was a retry error, the stacktrace was not visible until the retries finished (after ~5 min). What's more, in Kubernetes it's common that the POD was restarted sooner than the retries finish, which resulted in no StackTrace at all. 
fix #130
=> Add `kubernetes-api-retries` property

pom.xml, src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategy.java, src/main/java/com/hazelcast/kubernetes/KubernetesClient.java
* upgraded main hazelcast version to `4.0-SNAPSHOT`
* fixed compile errors
These changes at Hazelcast side broke our plugin master builds. 
https://github.com/hazelcast/hazelcast/commit/6ded404db9a829f4ed9787288941153638ffaf2f#diff-2e6b6ed6c2d9ee7d94f737362ef53f35
http://jenkins.hazelcast.com/view/Plugins/job/Kubernetes-master/
After we merge this PR, I will configure `Kubernetes-master` job as using new `4.0-compatibility` branch thus failure mails will be prevented.
=> Hazelcast 4.0 compatibility

pom.xml, src/main/java/com/hazelcast/kubernetes/KubernetesConfig.java, src/main/java/com/hazelcast/kubernetes/RestClient.java, src/test/java/com/hazelcast/kubernetes/KubernetesConfigTest.java
There are currently two different `nio` packages one of which is `com.hazelcast.nio` and the other one is `com.hazecast.internal.nio`. The changed ones have been replaced in the code and `com.hazecast.internal.nio` is added to bundle-plugin on pom.xml.
=> Move nio package to internal.nio

pom.xml
Updating Findbugs, because it's incompatible with Maven 3.6.0, see: https://stackoverflow.com/questions/53676071/maven-clean-command-java-util-collections-unmodifiablerandomaccesslist-to-prope
=> Update Findbugs version

README.md, pom.xml, src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategy.java, src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategyFactory.java, src/main/java/com/hazelcast/kubernetes/KubernetesApiEndpointResolver.java, src/main/java/com/hazelcast/kubernetes/KubernetesClient.java, src/main/java/com/hazelcast/kubernetes/KubernetesConfig.java, src/main/java/com/hazelcast/kubernetes/KubernetesProperties.java, src/test/java/com/hazelcast/kubernetes/KubernetesApiEndpointResolverTest.java, src/test/java/com/hazelcast/kubernetes/KubernetesClientTest.java
With this PR, our discovery plugin can filter hazelcast members via pod labels. This enhancement was tested at GKE cluster. If you want to test it, you can use `hasancelik/hazelcast:3.12.1-pod` docker image which includes related snapshot jars.
I am not sure should we make `service label` based discovery mech. deprecated, as @henrikarro mentioned [at related issue](https://github.com/hazelcast/hazelcast-kubernetes/issues/115#issuecomment-515350389), these parameter are still useful for some use-cases. To prevent `service-label  pod-label` confusion at user side, we can prepare a detailed README with some `yaml` samples. WDYT @leszko?
fix #115 
TODO:
=> discover hazelcast members via pod labels

src/main/java/com/hazelcast/kubernetes/KubernetesConfig.java, src/test/java/com/hazelcast/kubernetes/KubernetesConfigTest.java
This is not backwards-compatible change and therefore should be merged into `4.0-compatibility` branch and then release together with hazelcast `4.0`
fix #153
=> Change default value of `resolve-not-ready-addresses` to `true`

README.md, pom.xml, src/main/java/com/hazelcast/kubernetes/KubernetesConfig.java, src/test/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategyFactoryTest.java, src/test/java/com/hazelcast/kubernetes/KubernetesConfigTest.java
Same PR as https://github.com/hazelcast/hazelcast-kubernetes/pull/183 but for the master branch.
=> Retrieve the namespace from the filesystem instead of defaulting to "default".

rbac.yaml, src/main/java/com/hazelcast/kubernetes/KubernetesClient.java
If user forgot to assign RBAC, display the help message with the command to do it.
fix #209 
Note that it works only for:
- `default` namespace
- `default` service account
It's still an improvement, because it can help to set up Hazelcast on Kubernetes quicker for beginners.
=> Add rbac.yaml and related info message

src/main/java/com/hazelcast/kubernetes/KubernetesConfig.java, src/test/java/com/hazelcast/kubernetes/KubernetesConfigTest.java
When installed via helm chart, the property service.name is defined by the default in the Hazelcast chart and it cannot be used in conjunction with service-dns, it's needed to use an empty value for service.name, what is not allowed in the current version. This same fix was already done in the version 2.x, but it still was not fixed in the version 1.5.x, which prevents to use service-dns to connect with the version 3.x of Hazelcast.
=> Fix issue that was preventing to use service-dns for Hazelcast 3.x

src/main/java/com/hazelcast/kubernetes/RetryUtils.java
It used to use ExceptionUtils.rethrow from Hazelcast core, however its logic has changed and now it always throws HazelcastException.
=> Fix rethrowing exception

pom.xml, src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategyFactory.java, src/main/java/com/hazelcast/kubernetes/KubernetesClient.java, src/test/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategyFactoryTest.java
Note that:
- We will need to release with the com.hazelcast:hazelcast:4.1-SNAPSHOT dependency
- This change is 100% backward-compatible (new released `hazelcast-kubernetes` can be used with older hazelcast versions)
- Apart from auto-detection, the logs are improved
----------------------------
After this change, IMO the **newbie experience is great**.
1. Start Hazelcast on Kubernetes
```
$ kubectl run hazelcast --image=leszko/hazelcast
$ kubectl logs hazelcast
...
WARNING: Kubernetes API access is forbidden! Starting standalone. To use Hazelcast Kubernetes discovery configure the required RBAC. For 'default' service account in 'default' namespace execute: `kubectl apply -f https://raw.githubusercontent.com/hazelcast/hazelcast-kubernetes/master/rbac.yaml`
Jul 23, 2020 2:05:32 PM …
```
=> Implement auto detection

rbac.yaml
Add permission to query the "services" resource. Needed to support external client.
=> Update rbac.yaml to support external client

README.md, pom.xml, src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategy.java, src/main/java/com/hazelcast/kubernetes/KubernetesClient.java, src/test/java/com/hazelcast/kubernetes/KubernetesClientTest.java
With `3.12.11 IMDG release`, new metadata/group type introduced to define partition group based on Kubernetes node that Hazelcast cluster runs on. The discovery plugin should pass name of the node to the core SPI via using `discoverLocalMetadata` method like zone info. This method passes both `zone` and `node name` metadata. User can not enable two group types at the same time so cluster will decide which metadata will be used based on cluster config:
```
hazelcast:
partition-group:
enabled: true
group-type: NODE_AWARE
```
Here is the related [PRD](https://hazelcast.atlassian.net/wiki/spaces/PM/pages/1770291566/Kubernetes+Node+Aware+Partition+Grouping+Support).
These changes will be forward-port to master(2.2.x) branch.
IMDG core counterpart[ PR …
=> Add NODE_AWARE metadata support

README.md, src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategy.java, src/main/java/com/hazelcast/kubernetes/KubernetesClient.java, src/test/java/com/hazelcast/kubernetes/KubernetesClientTest.java
New metadata/group type introduced to define partition group based on Kubernetes node that Hazelcast cluster runs on. The discovery plugin should pass name of the node to the core SPI via using `discoverLocalMetadata` method like zone info. This method passes both `zone` and `node name` metadata. User can not enable two group types at the same time so cluster will decide which metadata will be used based on cluster config:
```
hazelcast:
partition-group:
enabled: true
group-type: NODE_AWARE
```
Here is the related [PRD](https://hazelcast.atlassian.net/wiki/spaces/PM/pages/1770291566/Kubernetes+Node+Aware+Partition+Grouping+Support).
(cherry-picked from commit 9f70794c8ffa4b836d899536d5642f1a7c04285b)
forward-port of https://github.com/hazelcast/hazelcast-kubernetes/pull/278
=> [FORWARD-PORT] Add NODE_AWARE metadata support 

.github/CODEOWNERS, .github/workflows/IMDG-snapshot.yml, .github/workflows/build-snapshot.yml, .github/workflows/pr-builder.yml, .github/workflows/publish-snapshot.yml, pom.xml
`publish-snapshot` build runs unit tests for every push to master and deploy snapshot jars to maven, replacement of jenkins based deploy build.
`IMDG-snapshot` build runs unit tests agains latest IMDG snapshot replacement of jenkins based master build.
=> Add publish-snapshot and IMDG-Snapshot actions

README.md
otherwise the kubectl call fails w/:
`error validating data: apiVersion not set`
=> Add apiVersion for service's yaml

src/main/java/com/hazelcast/kubernetes/KubernetesConfig.java, src/test/java/com/hazelcast/kubernetes/KubernetesConfigTest.java
Auto-mounting the serviceaccount-token is sometimes disabled to avoid giving applications
access to the kubernetes api when they don't need it. The current method of constructing
an instance of `KubernetesConfig` will try to read the information from the mounted serviceaccount
token even if a Service DNS is specified. This will fail in environments described earlier.
The information gathered from reading the serviceaccount-token fields is only relevant
for API mode. This commit will avoid reading the token if DNS Lookup is configured.
This fixes #284
=> Avoid reading serviceaccount-token in DNS Mode

README.md
Added documentation for the ability to specify a custom Hazelcast port through the `service-port` configuration property for DNS lookup. We're using a custom port for Hazelcast on our K8s cluster, and this got me searching for a while. The docs gave me the impression that the `service-port` could not be used for DNS lookup, while it's being used by `HazelcastKubernetesDiscoveryStrategy` to create a `DnsEndpointResolver` (line 44). Seeing this mentioned in the docs might save other people some time.
=> Added documentation for the ability to specify a custom Hazelcast port
