README.adoc
src/main/java/com/noctarius/hazelcast/kubernetes/DnsEndpointResolver.java
src/main/java/com/noctarius/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategy.java
src/main/java/com/noctarius/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategyFactory.java
src/main/java/com/noctarius/hazelcast/kubernetes/KubernetesProperties.java

Use SRV lookups for DNS resolving

---

src/main/java/com/noctarius/hazelcast/kubernetes/DnsEndpointResolver.java

@noctarius As discussed yesterday (@SchweizerischeBundesbahnen in Muntelier) we had a problem with hazelcast on openshift. We now debugged it and found out, that the problem is in the DnsEndpointResolver. As the response from openshift dns looks like this:
nslookup u219692-hazelcast.u219692-hazelcast.svc.cluster.local 172.30.0.1
Server:         172.30.0.1
Address:        172.30.0.1#53
Name:   u219692-hazelcast.u219692-hazelcast.svc.cluster.local
Address: 10.1.2.8
Name:   u219692-hazelcast.u219692-hazelcast.svc.cluster.local
Address: 10.1.5.28
Name:   u219692-hazelcast.u219692-hazelcast.svc.cluster.local
Address: 10.1.9.33
The current code adds three times the same ip address (loops the records and then calls "getByName" which always selects the frist answer and adds the ip 10.1.2.8 three …

Bugfix kubernetes via dns

---

README.adoc
checkstyle/ClassHeader.txt
checkstyle/checkstyle.xml
checkstyle/suppressions.xml
findbugs/findbugs-exclude.xml
pom.xml
src/main/java/com/hazelcast/kubernetes/DnsEndpointResolver.java
src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategy.java
src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategyFactory.java
src/main/java/com/hazelcast/kubernetes/KubernetesProperties.java
src/main/java/com/hazelcast/kubernetes/ServiceEndpointResolver.java
src/main/java/com/hazelcast/kubernetes/package-info.java
src/main/resources/META-INF/services/com.hazelcast.spi.discovery.DiscoveryStrategyFactory
src/test/java/com/hazelcast/kubernetes/KubernetesPropertiesTest.java

This PR;
- Aligns package namings with other Hazelcast plugins.
- Adds necessary mvn profiles, checkstyle/findbugs/master/release)
- Fixes checkstyle/findbugs errors.

Package and mvn profile arrangements after repo ownership transfer

---

pom.xml
src/test/java/com/hazelcast/kubernetes/DnsEndpointResolverTest.java
src/test/java/com/hazelcast/kubernetes/KubernetesDiscoveryStrategyFactoryTest.java
src/test/java/com/hazelcast/kubernetes/ServiceEndpointResolverTest.java

rat plugin is removed also. This should bring the test coverage to

Added new tests.

---

src/main/java/com/hazelcast/kubernetes/ServiceEndpointResolver.java
src/test/java/com/hazelcast/kubernetes/ServiceEndpointResolverTest.java

- refactor read token file for testing
- overall coverage up to 84%

Increase test coverage

---

pom.xml

Update kubernetes-client version

---

src/main/java/com/hazelcast/kubernetes/ServiceEndpointResolver.java
src/test/java/com/hazelcast/kubernetes/ServiceEndpointResolverTest.java

Resolves #43 
Please review @googlielmo

Added null check for endpointSubset.getAddresses()

---

src/main/java/com/hazelcast/kubernetes/ServiceEndpointResolver.java
src/test/java/com/hazelcast/kubernetes/ServiceEndpointResolverTest.java

- Fixes #53
- Adds a new test for it

Check endpoints.getSubsets() for null

---

src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategy.java
src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategyFactory.java
src/main/java/com/hazelcast/kubernetes/KubernetesProperties.java
src/main/java/com/hazelcast/kubernetes/ServiceEndpointResolver.java
src/test/java/com/hazelcast/kubernetes/ServiceEndpointResolverTest.java

Configurable version of feature commented on https://github.com/hazelcast/hazelcast-kubernetes/pull/37

Add configurable support for add endpoints of pods not still ready on kubernetes

---

src/main/java/com/hazelcast/kubernetes/KubernetesProperties.java

Fix javadoc

---

src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategyFactory.java

Add SERVICE_DNS_TIMEOUT to Properties

---

checkstyle/ClassHeader.txt
checkstyle/checkstyle.xml
checkstyle/suppressions.xml
findbugs/findbugs-exclude.xml
pom.xml
src/main/java/com/hazelcast/kubernetes/DefaultKubernetesClient.java
src/main/java/com/hazelcast/kubernetes/DnsEndpointResolver.java
src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategy.java
src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategyFactory.java
src/main/java/com/hazelcast/kubernetes/KubernetesClient.java
src/main/java/com/hazelcast/kubernetes/KubernetesClientException.java
src/main/java/com/hazelcast/kubernetes/KubernetesProperties.java
src/main/java/com/hazelcast/kubernetes/RetryKubernetesClient.java
src/main/java/com/hazelcast/kubernetes/RetryUtils.java
src/main/java/com/hazelcast/kubernetes/ServiceEndpointResolver.java
src/main/java/com/hazelcast/kubernetes/package-info.java
src/main/resources/META-INF/services/com.hazelcast.spi.discovery.DiscoveryStrategyFactory
src/test/java/com/hazelcast/kubernetes/DefaultKubernetesClientTest.java
src/test/java/com/hazelcast/kubernetes/DnsEndpointResolverTest.java
src/test/java/com/hazelcast/kubernetes/KubernetesDiscoveryStrategyFactoryTest.java
src/test/java/com/hazelcast/kubernetes/KubernetesPropertiesTest.java
src/test/java/com/hazelcast/kubernetes/RetryKubernetesClientTest.java
src/test/java/com/hazelcast/kubernetes/RetryUtilsTest.java
src/test/java/com/hazelcast/kubernetes/ServiceEndpointResolverTest.java

There are no code changes in this PR. Only updating licenses and adapting code formatting to the standard code formatting used in all Hazelcast projects.
fix #79

Format code and update licenses

---

pom.xml
src/main/java/com/hazelcast/kubernetes/DefaultKubernetesClient.java

Use the one copied into `hazelcast/hazelcast` instead.

Remove 'minimal-json' dependency

---

src/main/java/com/hazelcast/kubernetes/ServiceEndpointResolver.java

This will leak credentials via logs

Don't log the service account bearer token

---

README.md

Update README with recommendation to use StatefulSet

---

src/main/java/com/hazelcast/kubernetes/DnsEndpointResolver.java

Fix NPE handling in DnsExndpointResolver

---

README.md

This PR should be merged after releasing Kubernetes with ZONE_AWARE.

Update README after release 1.4

---

README.md

Update README with IBM Helm Chart and Kubernetes/OpenShift Operator

---

pom.xml
src/main/java/com/hazelcast/kubernetes/KubernetesConfig.java
src/main/java/com/hazelcast/kubernetes/RetryUtils.java

Address compilation and packaging issues because of
https://github.com/hazelcast/hazelcast/pull/15570.

Moved com.hazelcast.util to internal package

---

README.md

Change README to use YAML instead of XML

---

README.md
src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategy.java

* Make it only for the Kubernetes API Mode
* Log the discovered availability zone
fix #164
fix #155

Update fetching availability zone

---

README.md

Update README with info about Minikube and External Smart client

---

README.md

Improve description of "Outside Kubernetes Cluster"

---

README.md

Includes Istio and Embedded Kubernetes guides in README file.

Add guide links to doc.

---

README.md

Update granting RBAC permissions in README

---

src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategy.java

Update log level of logs related to ZONE_AWARE

---

src/main/java/com/hazelcast/kubernetes/KubernetesClient.java
src/test/java/com/hazelcast/kubernetes/KubernetesClientTest.java

Add extracting zone from node label: "topology.kubernetes.io/zone"

---

src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategyFactory.java
src/test/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategyFactoryTest.java

 Fix Auto Detection when Kubernetes Master is not available

---

README.md

Add information about CP Subsystem to README
